apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: argocd-learning

spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: argocd-app
      sources:
        direct: true

  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/ddprac/argocd-kargo-learning.git
            checkout:
              - branch: main
                path: ./src

        - uses: git-push
          config:
            path: ./src