apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app
  namespace: argocd-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-app
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
        - name: argocd-app
          image: argocd-app:v1
          ports:
           - containerPort: 9000
          env:
            - name: APP_ENV
              valueFrom:
                configMapKeyRef:
                  name: argocd-app-config
                  key: APP_ENV
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: argocd-app-secret
                  key: DB_PASSWORD