replicaCount: 2

image:
  repository: argocd-app
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000

app:
  environment: staging

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"