apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - prune-demo.yaml
namePrefix: dev-
patches:
  - path: configmap.yaml
  - path: deployment.yaml
images:
  - name: argocd-app
    newTag: v2